
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import clases.clsCat;
import clases.clsDog;
import controller.ctlPet;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SENA
 */  
public class frmPet extends javax.swing.JFrame {
    
    
        ctlPet ctlPet;
    /**
     * Creates new form view
     */
    public frmPet() {
        initComponents();
        this.ctlPet=new ctlPet();
        fillList();
        fillListCat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCodeCat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBornCat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbHealthCat = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtNameCat = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtColorCat = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cbBreedCat = new javax.swing.JComboBox<>();
        btnEliminarCat = new javax.swing.JButton();
        btnEditarCat = new javax.swing.JButton();
        btnBuscarCat = new javax.swing.JButton();
        btnCrearCat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CatList = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCodeDog = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBornDog = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbHealthDog = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNameDog = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtColorDog = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbBreedDog = new javax.swing.JComboBox<>();
        cbPedigreDog = new javax.swing.JCheckBox();
        btnEliminarDog = new javax.swing.JButton();
        btnEditarDog = new javax.swing.JButton();
        btnBuscarDog = new javax.swing.JButton();
        btnCrearDog = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DogList = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(102, 255, 102));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(240, 242, 244));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setText("Code");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 40, 20));

        txtCodeCat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCodeCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCodeCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeCatActionPerformed(evt);
            }
        });
        jPanel6.add(txtCodeCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 250, 30));

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setText("Born Year");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 70, 20));

        txtBornCat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBornCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBornCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBornCatActionPerformed(evt);
            }
        });
        jPanel6.add(txtBornCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 250, 30));

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setText("Health Status");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 20));

        cbHealthCat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbHealthCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sano", "Enfermo", " " }));
        cbHealthCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHealthCatActionPerformed(evt);
            }
        });
        jPanel6.add(cbHealthCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 250, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 460, 160));

        jPanel7.setBackground(new java.awt.Color(153, 255, 153));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel25.setText("Name");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 40, 20));

        txtNameCat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNameCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNameCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCatActionPerformed(evt);
            }
        });
        jPanel7.add(txtNameCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 210, 30));

        jLabel26.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel26.setText("Color");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 40, 20));

        txtColorCat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColorCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtColorCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorCatActionPerformed(evt);
            }
        });
        jPanel7.add(txtColorCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 210, 30));

        jLabel27.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel27.setText("Breed");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 40, 20));

        cbBreedCat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cbBreedCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Persa", "Egipcio", "Elfo", "Boon" }));
        jPanel7.add(cbBreedCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 460, 160));

        btnEliminarCat.setBackground(new java.awt.Color(153, 255, 153));
        btnEliminarCat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEliminarCat.setText("Eliminar");
        btnEliminarCat.setBorder(null);
        btnEliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCatActionPerformed(evt);
            }
        });
        jPanel5.add(btnEliminarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 140, 90));

        btnEditarCat.setBackground(new java.awt.Color(153, 255, 153));
        btnEditarCat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEditarCat.setText("Editar");
        btnEditarCat.setBorder(null);
        btnEditarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCatActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 140, 90));

        btnBuscarCat.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscarCat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnBuscarCat.setText("Buscar");
        btnBuscarCat.setBorder(null);
        btnBuscarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCatActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 140, 90));

        btnCrearCat.setBackground(new java.awt.Color(153, 255, 153));
        btnCrearCat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCrearCat.setText("Crear");
        btnCrearCat.setBorder(null);
        btnCrearCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCatActionPerformed(evt);
            }
        });
        jPanel5.add(btnCrearCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 140, 90));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CatManager", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        CatList.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        CatList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pets" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(CatList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CatList", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(153, 255, 153));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Code");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 40, 20));

        txtCodeDog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCodeDog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCodeDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeDogActionPerformed(evt);
            }
        });
        jPanel9.add(txtCodeDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 290, 30));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setText("Born Year");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 20));

        txtBornDog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBornDog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBornDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBornDogActionPerformed(evt);
            }
        });
        jPanel9.add(txtBornDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 290, 30));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setText("Health Status");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 20));

        cbHealthDog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbHealthDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sano", "Malestar", " " }));
        jPanel9.add(cbHealthDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 290, 30));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 460, 170));

        jPanel11.setBackground(new java.awt.Color(153, 255, 153));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Name");
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 20));

        txtNameDog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNameDog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNameDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameDogActionPerformed(evt);
            }
        });
        jPanel11.add(txtNameDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 310, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setText("Color");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 20));

        txtColorDog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColorDog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtColorDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorDogActionPerformed(evt);
            }
        });
        jPanel11.add(txtColorDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 310, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setText("Breed");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 40, 20));

        cbBreedDog.setBackground(new java.awt.Color(244, 244, 244));
        cbBreedDog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbBreedDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pastor Aleman", "Golden ", "Criollo" }));
        jPanel11.add(cbBreedDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 310, 30));

        cbPedigreDog.setBackground(new java.awt.Color(255, 255, 255));
        cbPedigreDog.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cbPedigreDog.setText("Pedigree");
        cbPedigreDog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbPedigreDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPedigreDogActionPerformed(evt);
            }
        });
        jPanel11.add(cbPedigreDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, -1));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 450, 170));

        btnEliminarDog.setBackground(new java.awt.Color(153, 255, 153));
        btnEliminarDog.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEliminarDog.setText("Eliminar");
        btnEliminarDog.setBorder(null);
        btnEliminarDog.setBorderPainted(false);
        btnEliminarDog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDogActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminarDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 130, 80));

        btnEditarDog.setBackground(new java.awt.Color(153, 255, 153));
        btnEditarDog.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEditarDog.setText("Editar");
        btnEditarDog.setBorder(null);
        btnEditarDog.setBorderPainted(false);
        btnEditarDog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDogActionPerformed(evt);
            }
        });
        jPanel4.add(btnEditarDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 130, 80));

        btnBuscarDog.setBackground(new java.awt.Color(153, 255, 153));
        btnBuscarDog.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnBuscarDog.setText("Buscar");
        btnBuscarDog.setBorder(null);
        btnBuscarDog.setBorderPainted(false);
        btnBuscarDog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDogActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscarDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 130, 80));

        btnCrearDog.setBackground(new java.awt.Color(153, 255, 153));
        btnCrearDog.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCrearDog.setText("Crear");
        btnCrearDog.setBorder(null);
        btnCrearDog.setBorderPainted(false);
        btnCrearDog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrearDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDogActionPerformed(evt);
            }
        });
        jPanel4.add(btnCrearDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, 80));

        jTabbedPane1.addTab("DogManager\n", jPanel4);

        DogList.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        DogList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pets" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(DogList);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("DogList", jPanel8);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 980, 450));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo .png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel1.setText("Pet Manager");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 550, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/huellas.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -170, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/huellas.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeCatActionPerformed

    private void txtBornCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBornCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBornCatActionPerformed

    private void txtNameCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCatActionPerformed

    private void txtColorCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorCatActionPerformed

    private void txtCodeDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeDogActionPerformed

    private void txtBornDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBornDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBornDogActionPerformed

    private void btnEliminarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDogActionPerformed
        try{
            String code= txtCodeDog.getText();
        if(code.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese codigo");
        } else {
            int codigo=Integer.parseInt(code);
            boolean found=false; 
            found=ctlPet.DeletePet(codigo,"Perro");
            limpiarDog();
            fillList();
            JOptionPane.showMessageDialog(this, "Mascota Eliminada");
            if(!found){
                JOptionPane.showMessageDialog(this,"Codigo no encontrado");
            }
        }
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }




    }//GEN-LAST:event_btnEliminarDogActionPerformed

    private void btnCrearDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDogActionPerformed
        try{
            int code= Integer.parseInt(txtCodeDog.getText());
            String name= txtNameDog.getText();
            String color= txtColorDog.getText();
            int bornYear=Integer.parseInt(txtBornDog.getText());
            String breed= cbBreedDog.getSelectedItem().toString();
            String health=cbHealthDog.getSelectedItem().toString();
            boolean pedigree = cbPedigreDog.isSelected();
            
            if(breed.equals("")|| name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
            }else{
                clsDog dog= new clsDog(code,name,bornYear,color,health,breed,pedigree);
                
                ctlPet.CreatePet(dog);
                limpiarDog();
                fillList();
                JOptionPane.showMessageDialog(this,"Mascota Registrada");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Digite un valor valido");
        }
    }//GEN-LAST:event_btnCrearDogActionPerformed

    private void btnBuscarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDogActionPerformed
        try{
            String code= txtCodeDog.getText();
            int codigo=Integer.parseInt(code);
            fillList();
            clsDog dog = (clsDog) ctlPet.searchPet(codigo, "Perro");
            if(dog==null) {
                JOptionPane.showMessageDialog(this, "Codigo no encontrado");
            } else {
                    txtNameDog.setText(dog.getName());
                    txtColorDog.setText(dog.getColor());
                    cbBreedDog.setSelectedItem(dog.getBreed());
                    txtBornDog.setText(Integer.toString(dog.getBorn_year()));
                    cbHealthDog.setSelectedItem(dog.getHealthStatus());
                    cbPedigreDog.setSelected(dog.isPedigree());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }
    }//GEN-LAST:event_btnBuscarDogActionPerformed

    private void btnEditarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDogActionPerformed
            try{
            int code= Integer.parseInt(txtCodeDog.getText());
            String name= txtNameDog.getText();
            String color= txtColorDog.getText();
            int bornYear=Integer.parseInt(txtBornDog.getText());
            String breed= cbBreedDog.getSelectedItem().toString();
            String health=cbHealthDog.getSelectedItem().toString();
            boolean pedigree = cbPedigreDog.isSelected();
            if(breed.equals("")|| name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
            }else{
                    clsDog dog= new clsDog(code,name,bornYear,color,health,breed,pedigree);
                    ctlPet.EditPet(dog);
                    
                    limpiarDog();
                    fillList();
                    JOptionPane.showMessageDialog(this,"Mascota actualizada");
        }
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }
    }//GEN-LAST:event_btnEditarDogActionPerformed

    private void txtNameDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameDogActionPerformed

    private void txtColorDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorDogActionPerformed

    private void cbPedigreDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPedigreDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPedigreDogActionPerformed

    private void btnEliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCatActionPerformed
        try{
            String code= txtCodeCat.getText();
        if(code.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese codigo");
        } else {
            int codigo=Integer.parseInt(code);
            boolean found=false; 
            found=ctlPet.DeletePet(codigo,"Gato");
            limpiarCat();
            fillListCat();
            JOptionPane.showMessageDialog(this, "Mascota Eliminada");
            if(!found){
                JOptionPane.showMessageDialog(this,"Codigo no encontrado");
            }
        }
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCatActionPerformed

    private void btnCrearCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCatActionPerformed
        try{
            int code= Integer.parseInt(txtCodeCat.getText());
            String name= txtNameCat.getText();
            String color= txtColorCat.getText();
            int bornYear=Integer.parseInt(txtBornCat.getText());
            String breed= cbBreedCat.getSelectedItem().toString();
            String health=cbHealthCat.getSelectedItem().toString();
            if(breed.equals("")|| name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
            }else{
                clsCat cat= new clsCat(code,name,bornYear,color,health,breed);
                ctlPet.CreatePet(cat);
                limpiarCat();
                fillListCat();
                JOptionPane.showMessageDialog(this,"Mascota Registrada");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Digite un valor valido");
        }
        
        
        
    }//GEN-LAST:event_btnCrearCatActionPerformed

    private void btnBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCatActionPerformed
        try{
            String code= txtCodeCat.getText();
            int codigo=Integer.parseInt(code);
            clsCat cat = (clsCat) ctlPet.searchPet(codigo, "Gato");
            if(cat==null) {
                JOptionPane.showMessageDialog(this, "Codigo no encontrado");
            } else {
                    txtNameCat.setText(cat.getName());
                    txtColorCat.setText(cat.getColor());
                    cbBreedCat.setSelectedItem(cat.getBreed());
                    txtBornCat.setText(Integer.toString(cat.getBorn_year()));
                    cbHealthCat.setSelectedItem(cat.getHealthStatus());
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }
        
        
    }//GEN-LAST:event_btnBuscarCatActionPerformed

    private void btnEditarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatActionPerformed
        try{
            int code= Integer.parseInt(txtCodeCat.getText());
            String name= txtNameCat.getText();
            String color= txtColorCat.getText();
            int bornYear=Integer.parseInt(txtBornCat.getText());
            String breed= cbBreedCat.getSelectedItem().toString();
            String health=cbHealthCat.getSelectedItem().toString();
         
            if(breed.equals("")|| name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
            }else{
                    clsCat cat= new clsCat(code,name,bornYear,color,health,breed);
                    ctlPet.EditPet(cat);
                    limpiarCat();
                    fillListCat();
                    JOptionPane.showMessageDialog(this,"Mascota actualizada");

        }
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }
    }//GEN-LAST:event_btnEditarCatActionPerformed

    private void cbHealthCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHealthCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHealthCatActionPerformed

    private void fillList(){
        LinkedList<clsDog> dogObjectList=null;
        DefaultListModel model = new DefaultListModel();
        int index=0;
        dogObjectList=ctlPet.fillList("Perro");
        for (clsDog dog : dogObjectList){
            String data=dog.getCode()+" | "+dog.getName()+" | "+dog.getBorn_year()+" | "+dog.getColor()+" | "+dog.getBreed()+" | "+dog.getHealthStatus();
            model.add(index, data);
            index++;
        }
        DogList.setModel(model);
    }
    
    private void limpiarDog(){
        txtCodeDog.setText("");
        txtNameDog.setText("");
        txtColorDog.setText("");
        txtBornDog.setText("");
        cbPedigreDog.setSelected(false);
    }
    
    private void fillListCat(){
        LinkedList<clsCat> catObjectList=null;
        DefaultListModel model = new DefaultListModel();
        int index=0;
        catObjectList=ctlPet.fillList("Gato");
        for (clsCat cat : catObjectList){
            String data=cat.getCode()+" | "+cat.getName()+" | "+cat.getBorn_year()+" | "+cat.getColor()+" | "+cat.getBreed()+" | "+cat.getHealthStatus();
            model.add(index, data);
            index++;
        }
        CatList.setModel(model);
    }
    
    private void limpiarCat(){
        txtCodeCat.setText("");
        txtNameCat.setText("");
        txtColorCat.setText("");
        txtBornCat.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> CatList;
    private javax.swing.JList<String> DogList;
    private javax.swing.JButton btnBuscarCat;
    private javax.swing.JButton btnBuscarDog;
    private javax.swing.JButton btnCrearCat;
    private javax.swing.JButton btnCrearDog;
    private javax.swing.JButton btnEditarCat;
    private javax.swing.JButton btnEditarDog;
    private javax.swing.JButton btnEliminarCat;
    private javax.swing.JButton btnEliminarDog;
    private javax.swing.JComboBox<String> cbBreedCat;
    private javax.swing.JComboBox<String> cbBreedDog;
    private javax.swing.JComboBox<String> cbHealthCat;
    private javax.swing.JComboBox<String> cbHealthDog;
    private javax.swing.JCheckBox cbPedigreDog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtBornCat;
    private javax.swing.JTextField txtBornDog;
    private javax.swing.JTextField txtCodeCat;
    private javax.swing.JTextField txtCodeDog;
    private javax.swing.JTextField txtColorCat;
    private javax.swing.JTextField txtColorDog;
    private javax.swing.JTextField txtNameCat;
    private javax.swing.JTextField txtNameDog;
    // End of variables declaration//GEN-END:variables
}
