/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import clases.clsCat;
import clases.clsDog;
import controller.ctlPet;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SENA
 */  
public class frmPet extends javax.swing.JFrame {
    
    
        ctlPet ctlPet;
        LinkedList<clsDog> dogObjectList=new LinkedList<>();
        LinkedList<clsCat> catObjectList=new LinkedList<>();
    /**
     * Creates new form view
     */
    public frmPet() {
        initComponents();
        this.ctlPet=new ctlPet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCodeCat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtBornCat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbHealthCat = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtNameCat = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtColorCat = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cbBreedCat = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        btnEliminarCat = new javax.swing.JButton();
        btnCrearCat = new javax.swing.JButton();
        btnBuscarCat = new javax.swing.JButton();
        btnEditarCat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PetList = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCodeDog = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBornDog = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbHealthDog = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        btnEliminarDog = new javax.swing.JButton();
        btnCrearDog = new javax.swing.JButton();
        btnBuscarDog = new javax.swing.JButton();
        btnEditarDog = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNameDog = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtColorDog = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbBreedDog = new javax.swing.JComboBox<>();
        cbPedigreDog = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(240, 242, 244));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel14.setText("Code");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 40, 20));

        txtCodeCat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCodeCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCodeCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeCatActionPerformed(evt);
            }
        });
        jPanel6.add(txtCodeCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 110, 20));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setText("Born Year");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 60, 20));

        txtBornCat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBornCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBornCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBornCatActionPerformed(evt);
            }
        });
        jPanel6.add(txtBornCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 110, 20));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel16.setText("Health Status");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 90, 20));

        cbHealthCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sano", "Enfermo", " " }));
        cbHealthCat.setBorder(null);
        jPanel6.add(cbHealthCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 110, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 140));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel25.setText("Name");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 20));

        txtNameCat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNameCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNameCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCatActionPerformed(evt);
            }
        });
        jPanel7.add(txtNameCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, 20));

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel26.setText("Color");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 40, 20));

        txtColorCat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColorCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtColorCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorCatActionPerformed(evt);
            }
        });
        jPanel7.add(txtColorCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, 20));

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel27.setText("Breed");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 40, 20));

        cbBreedCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Persa", "Egipcio", "Elfo", "Boon" }));
        cbBreedCat.setBorder(null);
        jPanel7.add(cbBreedCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, -1));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 270, 140));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarCat.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarCat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEliminarCat.setText("Eliminar");
        btnEliminarCat.setBorder(null);
        btnEliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCatActionPerformed(evt);
            }
        });
        jPanel12.add(btnEliminarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 80, 50));

        btnCrearCat.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearCat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCrearCat.setText("Crear");
        btnCrearCat.setBorder(null);
        btnCrearCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCatActionPerformed(evt);
            }
        });
        jPanel12.add(btnCrearCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 80, 50));

        btnBuscarCat.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarCat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnBuscarCat.setText("Buscar");
        btnBuscarCat.setBorder(null);
        btnBuscarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCatActionPerformed(evt);
            }
        });
        jPanel12.add(btnBuscarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 80, 50));

        btnEditarCat.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarCat.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEditarCat.setText("Editar");
        btnEditarCat.setBorder(null);
        btnEditarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCatActionPerformed(evt);
            }
        });
        jPanel12.add(btnEditarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 80, 50));

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 420, 90));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CatManager", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        PetList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pet1", "Pet2", "Pet3", "Pet4", "Pet5", "Pet6" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(PetList);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PetList\n", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("Code");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 40, 20));

        txtCodeDog.setBackground(new java.awt.Color(244, 244, 244));
        txtCodeDog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtCodeDog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCodeDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeDogActionPerformed(evt);
            }
        });
        jPanel9.add(txtCodeDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, 20));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("Born Year");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, 20));

        txtBornDog.setBackground(new java.awt.Color(244, 244, 244));
        txtBornDog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBornDog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtBornDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBornDogActionPerformed(evt);
            }
        });
        jPanel9.add(txtBornDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 20));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setText("Health Status");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, 20));

        cbHealthDog.setBackground(new java.awt.Color(244, 244, 244));
        cbHealthDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sano", "Malestar", " " }));
        cbHealthDog.setBorder(null);
        jPanel9.add(cbHealthDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, -1));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 140));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarDog.setBackground(new java.awt.Color(204, 204, 204));
        btnEliminarDog.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEliminarDog.setText("Eliminar");
        btnEliminarDog.setBorder(null);
        btnEliminarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDogActionPerformed(evt);
            }
        });
        jPanel10.add(btnEliminarDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 80, 50));

        btnCrearDog.setBackground(new java.awt.Color(204, 204, 204));
        btnCrearDog.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCrearDog.setText("Crear");
        btnCrearDog.setBorder(null);
        btnCrearDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDogActionPerformed(evt);
            }
        });
        jPanel10.add(btnCrearDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 50));

        btnBuscarDog.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarDog.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnBuscarDog.setText("Buscar");
        btnBuscarDog.setBorder(null);
        btnBuscarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDogActionPerformed(evt);
            }
        });
        jPanel10.add(btnBuscarDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 80, 50));

        btnEditarDog.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarDog.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEditarDog.setText("Editar");
        btnEditarDog.setBorder(null);
        btnEditarDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDogActionPerformed(evt);
            }
        });
        jPanel10.add(btnEditarDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 80, 50));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 380, 90));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel6.setText("Name");
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 20));

        txtNameDog.setBackground(new java.awt.Color(244, 244, 244));
        txtNameDog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNameDog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNameDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameDogActionPerformed(evt);
            }
        });
        jPanel11.add(txtNameDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, 20));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("Color");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, 20));

        txtColorDog.setBackground(new java.awt.Color(244, 244, 244));
        txtColorDog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtColorDog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtColorDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorDogActionPerformed(evt);
            }
        });
        jPanel11.add(txtColorDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, 20));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setText("Breed");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 40, 20));

        cbBreedDog.setBackground(new java.awt.Color(244, 244, 244));
        cbBreedDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pastor Aleman", "Golden ", "Criollo" }));
        cbBreedDog.setBorder(null);
        jPanel11.add(cbBreedDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, -1));

        cbPedigreDog.setBackground(new java.awt.Color(255, 255, 255));
        cbPedigreDog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbPedigreDog.setText("Pedigree");
        cbPedigreDog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbPedigreDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPedigreDogActionPerformed(evt);
            }
        });
        jPanel11.add(cbPedigreDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 80, -1));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 280, 140));

        jTabbedPane1.addTab("DogManager\n", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 620, 300));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setText("Pet Manager");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeCatActionPerformed

    private void txtBornCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBornCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBornCatActionPerformed

    private void txtNameCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCatActionPerformed

    private void txtColorCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorCatActionPerformed

    private void txtCodeDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeDogActionPerformed

    private void txtBornDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBornDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBornDogActionPerformed

    private void btnEliminarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDogActionPerformed
        try{
            String code= txtCodeDog.getText();
        if(code.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese codigo");
        } else {
            int codigo=Integer.parseInt(code);
            boolean found=false; 
            for (clsDog dog : dogObjectList){
                if(dog.getCode()==codigo){
                    dogObjectList.remove(dog);
                    found=true;
                    this.fillList();
                    limpiarDog();
                    JOptionPane.showMessageDialog(this, "Mascota Eliminada");
                    break;
                }
            }
            if(!found){
                JOptionPane.showMessageDialog(this,"Codigo no encontrado");
            }
        }
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }




    }//GEN-LAST:event_btnEliminarDogActionPerformed

    private void btnCrearDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDogActionPerformed
        try{
            int code= Integer.parseInt(txtCodeDog.getText());
            String name= txtNameDog.getText();
            String color= txtColorDog.getText();
            int bornYear=Integer.parseInt(txtBornDog.getText());
            String breed= cbBreedDog.getSelectedItem().toString();
            String health=cbHealthDog.getSelectedItem().toString();
            boolean pedigree = cbPedigreDog.isSelected();
            
            if(breed.equals("")|| name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
            }else{
                clsDog dog= new clsDog(code,name,bornYear,color,health,breed,pedigree);
                dogObjectList.add(dog);
                this.fillList();
                limpiarDog();
                JOptionPane.showMessageDialog(this,"Mascota Registrada");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Digite un valor valido");
        }
    }//GEN-LAST:event_btnCrearDogActionPerformed

    private void btnBuscarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDogActionPerformed

        String code= txtCodeDog.getText();
        int codigo=Integer.parseInt(code);
        clsDog dog = (clsDog) ctlPet.searchPet(codigo, "Perro");
        if(dog==null) {
            JOptionPane.showMessageDialog(this, "Codigo no encontrado");
        } else {
                txtNameDog.setText(dog.getName());
                txtColorDog.setText(dog.getColor());
                cbBreedDog.setSelectedItem(dog.getBreed());
                txtBornDog.setText(Integer.toString(dog.getBorn_year()));
                cbHealthDog.setSelectedItem(dog.getHealthStatus());
                cbPedigreDog.setSelected(dog.isPedigree());

        }
    }//GEN-LAST:event_btnBuscarDogActionPerformed

    private void btnEditarDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDogActionPerformed
            try{
            int code= Integer.parseInt(txtCodeDog.getText());
            String name= txtNameDog.getText();
            String color= txtColorDog.getText();
            int bornYear=Integer.parseInt(txtBornDog.getText());
            String breed= cbBreedDog.getSelectedItem().toString();
            String health=cbHealthDog.getSelectedItem().toString();
            boolean pedigree = cbPedigreDog.isSelected();
            if(breed.equals("")|| name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
            }else{
            for (clsDog dog : dogObjectList){
                if(dog.getCode()==code){    
                    dog.setName(name);
                    dog.setColor(color);
                    dog.setBreed(breed);
                    dog.setBorn_year(bornYear);
                    dog.setHealthStatus(health);
                    dog.setPedigree(pedigree);
                    fillList();
                    limpiarDog();
                    JOptionPane.showMessageDialog(this,"Mascota actualizada");
                    break;
                }
            }
        }
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }
    }//GEN-LAST:event_btnEditarDogActionPerformed

    private void txtNameDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameDogActionPerformed

    private void txtColorDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorDogActionPerformed

    private void cbPedigreDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPedigreDogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPedigreDogActionPerformed

    private void btnEliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCatActionPerformed
        try{
            String code= txtCodeCat.getText();
        if(code.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese codigo");
        } else {
            int codigo=Integer.parseInt(code);
            boolean found=false; 
            for (clsCat cat : catObjectList){
                if(cat.getCode()==codigo){
                    catObjectList.remove(cat);
                    found=true;
                    this.fillListCat();
                    limpiarCat();
                    JOptionPane.showMessageDialog(this, "Mascota Eliminada");
                    break;
                }
            }
            if(!found){
                JOptionPane.showMessageDialog(this,"Codigo no encontrado");
            }
        }
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCatActionPerformed

    private void btnCrearCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCatActionPerformed
        try{
            int code= Integer.parseInt(txtCodeCat.getText());
            String name= txtNameCat.getText();
            String color= txtColorCat.getText();
            int bornYear=Integer.parseInt(txtBornCat.getText());
            String breed= cbBreedCat.getSelectedItem().toString();
            String health=cbHealthCat.getSelectedItem().toString();
            if(breed.equals("")|| name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
            }else{
                clsCat cat= new clsCat(code,name,bornYear,color,health,breed);
                catObjectList.add(cat);
                this.fillListCat();
                limpiarCat();
                JOptionPane.showMessageDialog(this,"Mascota Registrada");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Digite un valor valido");
        }
        
        
        
    }//GEN-LAST:event_btnCrearCatActionPerformed

    private void btnBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCatActionPerformed
        try{
            String code= txtCodeCat.getText();
        if(code.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese codigo");
        } else {
            int codigo=Integer.parseInt(code);
            boolean found=false; 
            for (clsCat cat : catObjectList){
                if(cat.getCode()==codigo){
                    txtNameCat.setText(cat.getName());
                    txtColorCat.setText(cat.getColor());
                    cbBreedCat.setSelectedItem(cat.getBreed());
                    txtBornCat.setText(Integer.toString(cat.getBorn_year()));
                    cbHealthCat.setSelectedItem(cat.getHealthStatus());
                  
                    found=true;
                    break;
                }
            }
            if(!found){
                JOptionPane.showMessageDialog(this,"Codigo no encontrado");
            }
        }
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }
        
        
        
    }//GEN-LAST:event_btnBuscarCatActionPerformed

    private void btnEditarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatActionPerformed
        try{
            int code= Integer.parseInt(txtCodeCat.getText());
            String name= txtNameCat.getText();
            String color= txtColorCat.getText();
            int bornYear=Integer.parseInt(txtBornCat.getText());
            String breed= cbBreedCat.getSelectedItem().toString();
            String health=cbHealthCat.getSelectedItem().toString();
         
            if(breed.equals("")|| name.equals("")||color.equals("")){
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
            }else{
            for (clsCat cat : catObjectList){
                if(cat.getCode()==code){    
                    cat.setName(name);
                    cat.setColor(color);
                    cat.setBreed(breed);
                    cat.setBorn_year(bornYear);
                    cat.setHealthStatus(health);
                    fillListCat();
                    limpiarCat();
                    JOptionPane.showMessageDialog(this,"Mascota actualizada");
                    break;
                }
            }
        }
        }catch(Exception e){    
        JOptionPane.showMessageDialog(this,"Digite un valor valido");
        }
    }//GEN-LAST:event_btnEditarCatActionPerformed

    private void fillList(){
        DefaultListModel model = new DefaultListModel();
        int index=0;
        for (clsDog dog : dogObjectList){
            String data=dog.getName()+" "+dog.getBreed()+" "+dog.getColor()+" "+dog.getHealthStatus();
            model.add(index, data);
            index++;
        }
        PetList.setModel(model);
    }
    
    private void limpiarDog(){
        txtCodeDog.setText("");
        txtNameDog.setText("");
        txtColorDog.setText("");
        txtBornDog.setText("");
        cbPedigreDog.setSelected(false);
    }
    
    private void fillListCat(){
        DefaultListModel model = new DefaultListModel();
        int index=0;
        for (clsCat cat : catObjectList){
            String data=cat.getName()+" "+cat.getBreed()+" "+cat.getColor()+" "+cat.getHealthStatus();
            model.add(index, data);
            index++;
        }
        PetList.setModel(model);
    }
    
    private void limpiarCat(){
        txtCodeCat.setText("");
        txtNameCat.setText("");
        txtColorCat.setText("");
        txtBornCat.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> PetList;
    private javax.swing.JButton btnBuscarCat;
    private javax.swing.JButton btnBuscarDog;
    private javax.swing.JButton btnCrearCat;
    private javax.swing.JButton btnCrearDog;
    private javax.swing.JButton btnEditarCat;
    private javax.swing.JButton btnEditarDog;
    private javax.swing.JButton btnEliminarCat;
    private javax.swing.JButton btnEliminarDog;
    private javax.swing.JComboBox<String> cbBreedCat;
    private javax.swing.JComboBox<String> cbBreedDog;
    private javax.swing.JComboBox<String> cbHealthCat;
    private javax.swing.JComboBox<String> cbHealthDog;
    private javax.swing.JCheckBox cbPedigreDog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtBornCat;
    private javax.swing.JTextField txtBornDog;
    private javax.swing.JTextField txtCodeCat;
    private javax.swing.JTextField txtCodeDog;
    private javax.swing.JTextField txtColorCat;
    private javax.swing.JTextField txtColorDog;
    private javax.swing.JTextField txtNameCat;
    private javax.swing.JTextField txtNameDog;
    // End of variables declaration//GEN-END:variables
}
